import os
import re
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Frame, PageTemplate
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Use standard Times-Roman which is built-in to ReportLab
FONT_NAME = 'Times-Roman'
FONT_SIZE = 11

def convert_citations_to_superscript(text):
    """Convert [1], [2], etc. citations to superscript format for ReportLab."""
    # Replace [1], [2], [3] with <super>1</super>, <super>2</super>, etc.
    return re.sub(r'\[(\d+)\]', r'<super>\1</super>', text)

class ReportPDFGenerator:
    def __init__(self, filename, title):
        self.filename = filename
        self.title = title
        self.styles = getSampleStyleSheet()
        
        # Define specific styles based on requirements
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontName='Times-Roman',
            fontSize=16,
            alignment=1, # Center
            spaceAfter=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontName='Times-Roman',
            fontSize=13,
            fontWeight='bold',
            spaceBefore=12,
            spaceAfter=6
        ))
        
        self.styles.add(ParagraphStyle(
            name='NormalText',
            parent=self.styles['Normal'],
            fontName='Times-Roman',
            fontSize=11,
            leading=14, # Line spacing
            alignment=4 # Justified
        ))
        
        self.styles.add(ParagraphStyle(
            name='SourceItem',
            parent=self.styles['Normal'],
            fontName='Times-Roman',
            fontSize=10,
            leading=12,
            leftIndent=20,
            spaceBefore=4
        ))

    @staticmethod
    def draw_fixed_elements(canvas, doc):
        """Draws page numbers and metadata on every page."""
        canvas.saveState()
        
        # Page number
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.setFont('Times-Roman', 9)
        canvas.drawCentredString(LETTER[0]/2, 0.35 * inch, text)
        
        # Agent ID in bottom-left
        agent_id = getattr(doc, 'agent_id', 'Unknown')
        canvas.setFont('Times-Roman', 8)
        canvas.drawString(0.5 * inch, 0.35 * inch, f"Agent ID: {agent_id}")
        
        canvas.restoreState()

    def generate(self, content_data, agent_name="Agent", agent_id="Unknown"):
        """
        content_data expected format:
        {
            "summary": "...",
            "sections": [
                {"title": "...", "content": "..."},
                ...
            ],
            "sources": [
                {"title": "...", "url": "..."},
                ...
            ]
        }
        """
        doc = SimpleDocTemplate(self.filename, pagesize=LETTER, topMargin=0.75*inch, bottomMargin=0.75*inch)
        
        # Attach agent_id to doc so draw_fixed_elements can access it
        doc.agent_id = agent_id
        
        import datetime
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        story = []
        
        # Header Metadata
        story.append(Paragraph(f"Report Generated by: {agent_name}", self.styles['NormalText']))
        story.append(Paragraph(f"Date: {now}", self.styles['NormalText']))
        story.append(Spacer(1, 0.2*inch))
        
        # Title
        story.append(Paragraph(self.title, self.styles['ReportTitle']))
        story.append(Spacer(1, 0.2*inch))
        
        # Summary/Introduction
        if content_data.get("summary"):
            story.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
            summary_text = convert_citations_to_superscript(content_data["summary"])
            story.append(Paragraph(summary_text, self.styles['NormalText']))
            story.append(Spacer(1, 0.2*inch))

        # Main Sections
        for section in content_data.get("sections", []):
            story.append(Paragraph(section["title"], self.styles['SectionHeader']))
            section_content = convert_citations_to_superscript(section["content"])
            story.append(Paragraph(section_content, self.styles['NormalText']))
            story.append(Spacer(1, 0.1*inch))
            
        # Sources Page
        story.append(PageBreak())
        story.append(Paragraph("Sources and References", self.styles['SectionHeader']))
        story.append(Spacer(1, 0.1*inch))
        
        for source in content_data.get("sources", []):
            title = source.get("title", "Source")
            url = source.get("url", "#")
            # PDF links in reportlab use <a> tags
            link_html = f'<a href="{url}" color="blue">{title}</a>'
            story.append(Paragraph(f"• {link_html}<br/><i>{url}</i>", self.styles['SourceItem']))
            story.append(Spacer(1, 0.05*inch))
            
        # Build the PDF
        doc.build(story, onFirstPage=self.draw_fixed_elements, onLaterPages=self.draw_fixed_elements)
        return self.filename

if __name__ == "__main__":
    # Test generation
    test_data = {
        "summary": "This is a test summary for the report generation tool. It covers the basic functionality and layout requirements.",
        "sections": [
            {"title": "Implementation Progress", "content": "The PDF generator is currently being implemented using the reportlab library. It supports Times New Roman, borders, and page numbers as requested by the user."},
            {"title": "Future Steps", "content": "Next steps include integrating this with the LLM synthesis logic to process data from various sources like web searches and other agents."}
        ],
        "sources": [
            {"title": "ReportLab Documentation", "url": "https://www.reportlab.com/docs/reportlab-userguide.pdf"},
            {"title": "Google Gemini API", "url": "https://ai.google.dev/"}
        ]
    }
    gen = ReportPDFGenerator("test_report.pdf", "AI Integration Test Report")
    gen.generate(test_data)
    print("Test report generated: test_report.pdf")
